name: Test react App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        # run: echo 
        uses: actions/checkout@v3
      - name: Install dependences
        #run: npm install
        run: npm ci
      - name: Test application
        run: npm run test
